# Generated by Django 4.2.16 on 2024-11-20 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScriptName', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['ScriptName'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('EmailId', models.CharField(max_length=30)),
                ('ContactNo', models.CharField(max_length=15)),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Img', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['UserName'],
            },
        ),
        migrations.CreateModel(
            name='SellInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selldate', models.DateField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('ScriptName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.scriptinfo')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BuyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buydate', models.DateField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('ScriptName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.scriptinfo')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.userinfo')),
            ],
        ),
    ]
