# Generated by Django 4.2.16 on 2025-01-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placename', models.CharField(max_length=30)),
                ('Days', models.IntegerField(max_length=30)),
                ('Nights', models.IntegerField(max_length=15)),
                ('Img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='buyinfo',
            name='Amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='buyinfo',
            name='Buydate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='buyinfo',
            name='Quantity',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='buyinfo',
            name='Rate',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellinfo',
            name='Amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellinfo',
            name='Quantity',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellinfo',
            name='Rate',
            field=models.PositiveBigIntegerField(),
        ),
    ]
